export const FEATURE_KEYS = {
  DASHBOARD: "building_info_enabled",
  USER_PROFILE: "profile_section",
  HISTORY: "chat_history",
  USER_BUILDING_LIST: "building_info_enabled",
  COMPARATIVE_BUILDING: "comparative_building_data_enabled",
  LEASE_LOI: "lease_loi_enabled",
  LOI_DOCUMENTS: "loi_documents_enabled",
  CRE_NEWS: "cre_news",
  USER_CHAT: "leases_agreement_data_enabled",
  PORTFOLIO_CHAT: "portfolio_insights_enabled",
  BUILDING_CHAT: "building_chat_enabled",
  COMPARATIVE_CHAT: "comparative_chat_enabled",

  Third_PARTY_CHAT: "third_party_enabled",
  COLLEAGUE_CHAT: "employee_contact_enabled",
  MARKET_CHAT: "comps_enabled",
  TENANT_CHAT: "tenant_information_enabled",
  TENANT_MARKET: "tenants_in_the_market_enabled",
  FIRESAFETY: "fire_safety_enabled",
  WORKLETTER: "project_management_enabled",
  DCT_CHAT: "dct_enabled",

  CHAT_SYSTEM: "gemini_chat_enabled",
  GEMINI: "gemini_chat_enabled",
  EMAIL_DRAFTING: "email_drafting_enabled",
  AI_LEASE_ABSTRACT: "ai_lease_abstract_enabled",
  NOTES: "notes_enabled",
  INFORMATION_COLLABORATION: "information_collaboration_enabled",
  FORUM: "forum_enabled",
  SUBLEASE: "sublease_tracker_enabled",
  RENEWAL: "renewal_tracker_enabled",
  DEAL: "deal_tracker_enabled",
  TOUR: "tour_enabled",
  YARDI: "yardi_enabled",
  CALCULATOR: "calculator_enabled",
  BENCHMARK: "det_enabled",
  DISTILLED_COMP: "dct_enabled",
};
